services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/2security/Dockerfile
    container_name: ctl_security
    image: adri/security:latest
    ports:
      - "${PORT_SSH}:22"
    env_file:
      - .env
    volumes:
      - ./logs:/root/logs