services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/2security/Dockerfile
    container_name: ctl_security
    image: adri/security:latest
    ports:
      - 3457:22
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs