FROM adri/nginx:latest

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app/inicio

COPY proyectos/inicio/package*.json ./
RUN npm install

COPY proyectos/inicio ./

RUN mkdir -p /root/admin/react
COPY ./dockerfiles/4react/admin/start.sh /root/admin/react/start.sh
RUN chmod +x /root/admin/react/start.sh

ENTRYPOINT ["/root/admin/react/start.sh"]