# Heredar de tu imagen 2security
FROM adri/security 

RUN mkdir -p /root/admin/nginx
COPY ./dockerfiles/3nginx/admin/start.sh /root/admin/nginx/start.sh
RUN chmod +x /root/admin/nginx/start.sh

ENTRYPOINT ["/root/admin/nginx/start.sh"]