FROM adri/security:latest

RUN apt-get update && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/admin/nginx
COPY ./dockerfiles/3nginx/admin/start.sh /root/admin/nginx/start.sh
RUN chmod +x /root/admin/nginx/start.sh

ENTRYPOINT ["/root/admin/nginx/start.sh"]