FROM adri/security:latest

RUN apt-get update && apt-get install -y curl ca-certificates openssl gnupg \
  && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/admin/node
COPY ./dockerfiles/6node/admin/start.sh /root/admin/node/start.sh
RUN chmod +x /root/admin/node/start.sh

EXPOSE 3456
ENTRYPOINT ["/root/admin/node/start.sh"]
