version: "3.8"

services:
  inicio:
    image: adri/inicio:latest
    container_name: ctl_inicio
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/5inicio/Dockerfile
    env_file: 
      - .env
    ports:
      - 3000:3000   # App Vite (dev/preview)
      - ${PORT_WWW}:80        # Nginx (si tu capa lo usa)
      - ${PORT_SSH}:22        # SSH (si tu imagen lo trae)
    volumes:
      - ./logs:/root/logs
    networks:
      - red_adriana
    restart: always

networks:
  red_adriana:
    external: true