FROM adri/node:latest

WORKDIR /app/api-pelis-pokemon

COPY proyectos/api-pelis-pokemon/package*.json ./
RUN npm install

COPY proyectos/api-pelis-pokemon ./
RUN npm run build

RUN mkdir -p /root/admin/nest
COPY ./dockerfiles/8nest/admin/start.sh /root/admin/nest/start.sh
RUN chmod +x /root/admin/nest/start.sh

EXPOSE 3444 3456
ENTRYPOINT ["/root/admin/nest/start.sh"]
