# syntax=docker/dockerfile:1
FROM adri/node:latest

WORKDIR /app/pokeapi-adriana

COPY proyectos/pokeapi-adriana/package*.json ./
RUN npm install

COPY proyectos/pokeapi-adriana ./
RUN npm run build

RUN mkdir -p /root/admin/next
COPY ./dockerfiles/7next/admin/start.sh /root/admin/next/start.sh
COPY ./dockerfiles/7next/admin/https-server.mjs /app/pokeapi-adriana/https-server.mjs
RUN chmod +x /root/admin/next/start.sh

EXPOSE 3443 3456
ENTRYPOINT ["/root/admin/next/start.sh"]
