# syntax=docker/dockerfile:1
FROM adri/node:latest

WORKDIR /app/Tienda-Online

COPY proyectos/Tienda-Online/package*.json ./
COPY proyectos/Tienda-Online/apps/api/package.json ./apps/api/package.json
COPY proyectos/Tienda-Online/apps/web/package.json ./apps/web/package.json
RUN npm install

COPY proyectos/Tienda-Online ./
RUN npm run build -w apps/api

RUN mkdir -p /root/admin/nest
COPY ./dockerfiles/05nest/admin/start.sh /root/admin/nest/start.sh
RUN chmod +x /root/admin/nest/start.sh

EXPOSE 3444 3456
ENTRYPOINT ["/root/admin/nest/start.sh"]
