FROM adri/nginx:latest

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
  && apt-get install -y nodejs \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app/inicio

COPY proyectos/inicio/package*.json ./
RUN npm install

COPY proyectos/inicio ./

RUN mkdir -p /root/admin/inicio
COPY ./dockerfiles/5inicio/admin/start.sh /root/admin/inicio/start.sh
RUN chmod +x /root/admin/inicio/start.sh

EXPOSE 3000
ENTRYPOINT ["/root/admin/inicio/start.sh"]
