services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/1ubbase/dockerfile
    container_name: ctlubase
    image: adriana/ubbase
    ports:
      - "${PORT_SSH}:22"
    env_file:
      - .env
    volumes:
      - ./logs:/root/logs
    networks:
      pbase_network:
        ipv4_address: 192.168.10.1
networks:
  pbase_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24